version: "3.8"

services:
  db:
    image: mysql:8.0
    container_name: db-server
    restart: unless-stopped
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_DATABASE: everybox
      MYSQL_USER: everybox_user
      MYSQL_PASSWORD: ${DB_USER_PASSWORD}
    volumes:
      - db-data:/var/lib/mysql

  be:
    image: yujin20fd/everybox-be:latest
    container_name: be-server
    restart: unless-stopped
    ports:
      - "8080:8080"
    depends_on:
      - db
    volumes:
      - ./config:/config
    environment:
      - TZ=Asia/Seoul

volumes:
  db-data: